// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mutjcytgiwdtukjbooqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11dGpjeXRnaXdkdHVramJvb3F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMDI1ODUsImV4cCI6MjA2Mzc3ODU4NX0.pwzwnj7zgt746LNhyDNSHoRJSCjbGyS7F-0EFGp_Tv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);